### ISSUE TITLE
💗 your screenshot!  These are great utilities to write for yourself.

### ISSUE THREAD

**Issue by PySimpleGUI** [FelipeeM/color-picker-on-the-screen#1]
Thank you for taking the time to post a GIF of your program.  The difference in seeing a GUI in a readme versus no images is enormous.  Visitors, no doubt, will pause and look at your project.

There's a Color Picture Demo Program that I wrote despite having 6 or more color tools that include a picker. 

https://www.pysimplegui.org/en/latest/Demos/#demo_pil_color_pickerpy

 I like the simplicity of your design.  I love these little utilities that are practical and useful on a daily basis.

**Comment by FelipeeM** [comment]
Thanks!
I made this program to help in everyday life.
I like your model!
